{% set name = "matplotlib-label-lines" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cphyc/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d2c85b7555c2741f446b73f42595e1febb3eb9ad4dbcbba18f8d8c6718d7e921

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6
    - numpy
    - matplotlib-base

test:
  imports:
    - labellines

about:
  home: https://github.com/cphyc/matplotlib-label-lines
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Embeds labels in matplotlib lines
  doc_url: https://github.com/cphyc/matplotlib-label-lines

extra:
  recipe-maintainers:
    - kalling
    - pigattol
