{% set name = "matplotlib-label-lines" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cphyc/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1a390199d0c7a2cf959a50161d7a4d3b8cef7068b134e7876234892de5a48b87

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - more-itertools

test:
  requires:
    - python {{ python_min }}
  imports:
    - labellines

about:
  home: https://github.com/cphyc/matplotlib-label-lines
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Embeds labels in matplotlib lines
  doc_url: https://github.com/cphyc/matplotlib-label-lines

extra:
  recipe-maintainers:
    - kalling
    - pigattol
