{% set name = "matplotlib-label-lines" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cphyc/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4f13b628c5bcebfb055d9b56d348f795e1cdfb2cfed0d0587eac67cfd1ddf71b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6
    - numpy
    - matplotlib-base
    - more-itertools

test:
  imports:
    - labellines

about:
  home: https://github.com/cphyc/matplotlib-label-lines
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Embeds labels in matplotlib lines
  doc_url: https://github.com/cphyc/matplotlib-label-lines

extra:
  recipe-maintainers:
    - kalling
    - pigattol
