{% set name = "matplotlib-label-lines" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cphyc/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ca5d01b01e0904cbd994133e08c4459b791cace824fe772e8f0f9ac92a9b806e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - more-itertools

test:
  requires:
    - python {{ python_min }}
  imports:
    - labellines

about:
  home: https://github.com/cphyc/matplotlib-label-lines
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Embeds labels in matplotlib lines
  doc_url: https://github.com/cphyc/matplotlib-label-lines

extra:
  recipe-maintainers:
    - kalling
    - pigattol
